@KatalogApi_HostAddress = http://localhost:5017
@ApiKey = HemligNyckel123

### 1. Hämta alla prylar från katalogen
GET {{KatalogApi_HostAddress}}/api/items
Accept: application/json
X-Api-Key: {{ApiKey}}

### 2. Hämta en specifik pryl (t.ex. Kaffebryggaren med ID 5)
GET {{KatalogApi_HostAddress}}/api/items/2
Accept: application/json
X-Api-Key: {{ApiKey}}

### 3. Testa att skicka in fel API-nyckel (Ska ge 401 Unauthorized!)
GET {{KatalogApi_HostAddress}}/api/items
Accept: application/json
X-Api-Key: FelLösenord123

### 4. Skapa en helt ny pryl i databasen (POST)
POST {{KatalogApi_HostAddress}}/api/items
Accept: application/json
Content-Type: application/json
X-Api-Key: {{ApiKey}}

{
  "name": "Skruvdragare",
  "type": 2,
  "description": "Bosch 18V med dubbla batterier.",
  "status": 0,
  "placement": "Verktygslådan",
  "purchaseDate": "2024-02-27T10:00:00Z"
}

### 5. Uppdatera en pryl (PUT) - t.ex. ändra status till Trasig (3)
PUT {{KatalogApi_HostAddress}}/api/items/7
Accept: application/json
Content-Type: application/json
X-Api-Key: {{ApiKey}}

{
  "id": 7,
  "name": "Skruvdragare",
  "type": 3,
  "description": "Bosch 18V - Nu lagad och fungerar!",
  "status": 0,
  "placement": "Verktygslådan",
  "purchaseDate": "2024-02-27T10:00:00Z"
}

### 6. Ta bort en pryl (DELETE)
DELETE {{KatalogApi_HostAddress}}/api/items/3
Accept: application/json
X-Api-Key: {{ApiKey}}