// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SOS100_LoanAPI.Data;

#nullable disable

namespace SOS100_LoanAPI.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20260306012017_RemoveActiveItemKey")]
    partial class RemoveActiveItemKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SOS100_LoanAPI.Domain.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BorrowerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LoanedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId")
                        .IsUnique()
                        .HasFilter("\"ReturnedAt\" IS NULL");

                    b.HasIndex("ReturnedAt");

                    b.ToTable("Loans");
                });
#pragma warning restore 612, 618
        }
    }
}
